### ISSUE TITLE
Program not starting

### ISSUE THREAD

**Issue by LabAviator** [ash47/OmegleMiddleMan#22]
So whenever I try to run the "Run.bat" -file I get the following error in the command window:

`C:\Users\Potato\Downloads\OmegleMiddleMan-master>node app.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'qs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Potato\Downloads\OmegleMiddleMan-master\omegle.js:7:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)`

**Comment by ash47** [comment]
You need to run "npm install" from that directory, that will download and
install all the missing modules such as querystring.
