### ISSUE TITLE
Port 3000 already in use!

### ISSUE THREAD

**Issue by karimawii** [ash47/OmegleMiddleMan#66]
Says this whenever I open run.bat 
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Object.<anonymous> (E:\Karim\Programs\OmegleMiddleMan-master\app.js:624:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3000
}
```

**Comment by ash47** [comment]
You already have another app listening on port 3000, close the other app or
change the port this app listens on.

**Comment by karimawii** [comment]
I understand that, but I don't know what app I'm using uses the same port cause it's giving me this when I open it in chrome
![image](https://user-images.githubusercontent.com/69881381/122627894-cdc61900-d0b2-11eb-8685-a7ea259d05b1.png)

Also I don't know how to change the port.

**Comment by ash47** [comment]
You can edit the following line to change the port number, e.g. to 3001 or
another number.

https://github.com/ash47/OmegleMiddleMan/blob/master/app.js#L623
